### ISSUE TITLE
Error when log transforming data

### ISSUE THREAD

**Issue by venslovg** [ciernialab/MicrogliaMorphologyR#2]
Hi there, just wanted to bring to your attention that there is a deprecated function within the package. When running the code: ```data_2xLPS_logtransformed <- transform_log(data_2xLPS, 1, start=9, end=35)``` an error message pops up: ```Warning: `funs()` was deprecated in dplyr 0.8.0.``` with recommendations for substitution functions.

**Comment by jenn-kim** [comment]
Thanks for bringing this to our attention! The transform_log function has been updated.
